# Generated by Django 6.1.1 on 2026-09-13 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[('BKASH', 'bKash'), ('NAGAD', 'Nagad'), ('COD', 'Cash on Delivery'), ('CORPORATE_POSTPAID', 'Corporate Postpaid (Invoiced)')], max_length=20),
        ),
    ]
