# Generated by Django 6.1.1 on 2026-09-12 17:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryIncentive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('is_paid', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='incentive', to='orders.order')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incentives', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GPSPing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=10)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gps_pings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-recorded_at'],
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_number', models.CharField(max_length=50, unique=True)),
                ('vehicle_type', models.CharField(choices=[('BIKE', 'Motorbike'), ('VAN', 'Van'), ('RICKSHAW_VAN', 'Rickshaw Van'), ('TRUCK', 'Truck')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('assigned_staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicles', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OfflineSyncEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('local_event_id', models.CharField(help_text='Client-generated UUID for idempotency', max_length=100)),
                ('event_type', models.CharField(choices=[('DELIVERY_CONFIRM', 'Delivery Confirm'), ('BOTTLE_COLLECT', 'Bottle Collect'), ('BOTTLE_CONDITION', 'Bottle Condition Update'), ('PAYMENT_COLLECT', 'Payment Collect'), ('EXCEPTION_REPORT', 'Exception Report')], max_length=30)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('device_reference', models.CharField(blank=True, max_length=100)),
                ('occurred_at', models.DateTimeField(help_text='When the action actually happened on the device')),
                ('synced_at', models.DateTimeField(blank=True, null=True)),
                ('sync_status', models.CharField(choices=[('QUEUED', 'Queued on Device'), ('SYNCING', 'Syncing'), ('ACCEPTED', 'Accepted'), ('CONFLICT', 'Conflict - Needs Review'), ('REJECTED', 'Rejected')], default='QUEUED', max_length=10)),
                ('conflict_note', models.TextField(blank=True)),
                ('related_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.order')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offline_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['occurred_at'],
                'unique_together': {('staff', 'local_event_id')},
            },
        ),
    ]
