# Generated by Django 6.1.1 on 2026-09-13 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='purpose',
            field=models.CharField(choices=[('REGISTRATION', 'Registration'), ('LOGIN', 'Login'), ('GUEST_ORDER', 'Guest Order'), ('ACTION_VERIFY', 'Important Action'), ('PASSWORD_RESET', 'Password Reset')], max_length=20),
        ),
    ]
