# Generated by Django 6.1.1 on 2026-09-14
# Adds Bangladesh-context address fields: house_name (ফ্ল্যাট/বাড়ির নাম) and
# landmark (নিকটস্থ পরিচিত স্থান) -- GPS/map addresses alone often aren't
# precise enough for narrow lanes ("goli") in BD cities, so delivery staff
# need a human-readable landmark to actually find the address.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_otp_phone_alter_user_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='house_name',
            field=models.CharField(blank=True, help_text='ফ্ল্যাট/বাড়ির নাম বা নম্বর (যেমন: বাড়ি ১২, ফ্ল্যাট ৩বি)', max_length=150),
        ),
        migrations.AddField(
            model_name='address',
            name='landmark',
            field=models.CharField(blank=True, help_text='নিকটস্থ পরিচিত স্থান (যেমন: আল-ফালাহ মসজিদের পাশে) -- ম্যাপে সবসময় নির্ভুলভাবে ঠিকানা পাওয়া যায় না, তাই এটা staff-কে খুঁজে পেতে সাহায্য করে।', max_length=200),
        ),
    ]
