# Generated by Django 6.1.1 on 2026-09-12 17:40
# Rewritten for aggregate bottle tracking (BottleInventory / CustomerBottleHolding
# / InventoryWriteOff) instead of per-unit BottleUnit/BottleTransaction, per the
# final spec's "no per-unit tracking" requirement. Not yet applied to any real
# database, so edited in place rather than layered with a follow-up migration.
# Depends on 'orders' now (InventoryWriteOff.related_order) instead of the other
# way around.

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BottleInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('available_count', models.PositiveIntegerField(default=0)),
                ('damaged_count', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to='catalog.product')),
            ],
        ),
        migrations.CreateModel(
            name='CustomerBottleHolding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bottle_holdings', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_holdings', to='catalog.product')),
            ],
            options={
                'unique_together': {('customer', 'product')},
            },
        ),
        migrations.CreateModel(
            name='InventoryWriteOff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('reason', models.CharField(choices=[('SANITIZATION_DAMAGE', 'Found Damaged During Sanitization'), ('FIELD_COLLECTION_DAMAGED', 'Damaged -- Collected From Customer'), ('FIELD_COLLECTION_UNUSABLE', 'Unusable -- Collected From Customer'), ('LOST', 'Reported Lost'), ('OTHER', 'Other')], max_length=32)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='write_offs', to='catalog.product')),
                ('related_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='write_offs', to='orders.order')),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='write_offs_logged', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
