# Generated by Django 6.1.1 on 2026-09-12 17:40

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('order_type', models.CharField(choices=[('FIRST_PURCHASE', 'First Purchase'), ('REFILL', 'Refill')], max_length=20)),
                ('status', models.CharField(choices=[('CREATED', 'Order Created'), ('CONFIRMED', 'Admin Confirmed'), ('ASSIGNED', 'Staff Assigned'), ('OUT_FOR_DELIVERY', 'Out for Delivery'), ('DELIVERED', 'Delivered'), ('FAILED', 'Failed / Exception'), ('CANCELLED', 'Cancelled')], default='CREATED', max_length=20)),
                ('payment_method', models.CharField(choices=[('BKASH', 'bKash'), ('NAGAD', 'Nagad'), ('COD', 'Cash on Delivery')], max_length=10)),
                ('is_express', models.BooleanField(default=False)),
                ('express_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('delivery_charge', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('water_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('bottle_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('bottles_delivered', models.PositiveIntegerField(default=0)),
                ('empties_collected_good', models.PositiveIntegerField(default=0)),
                ('empties_collected_damaged', models.PositiveIntegerField(default=0)),
                ('is_subscription_order', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_orders', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to=settings.AUTH_USER_MODEL)),
                ('delivery_address', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='accounts.address')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DeliveryException',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('CUSTOMER_UNAVAILABLE', 'Customer Unavailable'), ('WRONG_ADDRESS', 'Wrong Address'), ('CUSTOMER_REFUSED', 'Customer Refused Delivery'), ('PAYMENT_ISSUE', 'Payment Issue'), ('BOTTLE_ISSUE', 'Bottle Issue'), ('OTHER', 'Other')], max_length=30)),
                ('note', models.TextField(blank=True)),
                ('is_resolved', models.BooleanField(default=False)),
                ('resolution_note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('reported_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exceptions', to='orders.order')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('unit_water_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit_bottle_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.product')),
            ],
        ),
        migrations.CreateModel(
            name='RefillReminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(default='Your next refill may be due.', max_length=255)),
                ('is_sent', models.BooleanField(default=False)),
                ('scheduled_for', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refill_reminders', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interval', models.CharField(choices=[('WEEKLY', 'Weekly'), ('BIWEEKLY', 'Bi-weekly'), ('MONTHLY', 'Monthly'), ('CUSTOM', 'Custom')], default='WEEKLY', max_length=10)),
                ('custom_days', models.PositiveIntegerField(blank=True, help_text='Used when interval=CUSTOM', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('next_run_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.address')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.product')),
            ],
        ),
    ]
