# Generated by Django 6.1.1 on 2026-09-13 10:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b2b', '0001_initial'),
        ('orders', '0002_order_discount_amount_order_promo_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='corporate_client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders_placed', to='b2b.corporateclient'),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('BKASH', 'bKash'), ('NAGAD', 'Nagad'), ('COD', 'Cash on Delivery'), ('CORPORATE_POSTPAID', 'Corporate Postpaid (Invoiced)')], max_length=20),
        ),
    ]
