# Generated by Django 6.1.1 on 2026-09-14
# Adds Order.placed_by -- an audit trail for orders a staff member places on
# behalf of a phone-call customer (Quick Staff Assignment / Admin Order
# Placement features), distinct from self-service and guest-checkout orders
# where this stays null.

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_corporate_client_alter_order_payment_method'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='placed_by',
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                related_name='phone_orders_placed', to=settings.AUTH_USER_MODEL,
                help_text='Admin/staff যদি ফোন কলে কাস্টমারের হয়ে অর্ডার বসিয়ে থাকে, সেই staff -- self-service/guest অর্ডারে null থাকে।',
            ),
        ),
    ]
